version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_USER=django_user
      - POSTGRES_DB=django_db

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"

    depends_on:
      - db
    env_file:
      - ./.env